name: Deployment pipeline

on:
  pull_request:
  push:
    branches: [main]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: "18.17"
          cache: "yarn"

      - name: Install dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn build && yarn test
